//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.AddingPermissions = new HashSet<AddingPermission>();
            this.ExportDetails = new HashSet<ExportDetail>();
            this.MovementPermissions = new HashSet<MovementPermission>();
            this.WithdrawPerms = new HashSet<WithdrawPerm>();
        }
    
        public int Id { get; set; }
        public string VIN { get; set; }
        public string PlateNo { get; set; }
        public string MotorNo { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Storing_Master_Id { get; set; }
        public Nullable<bool> IsSold { get; set; }
        public Nullable<bool> IsReceived { get; set; }
        public Nullable<int> SalesOrderID { get; set; }
        public Nullable<int> modelID { get; set; }
        public Nullable<int> ManufacturingYearID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> CarCateID { get; set; }
        public Nullable<int> CurrentStoreID { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> purchaseOrderDetailsId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddingPermission> AddingPermissions { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual CarsCategory CarsCategory { get; set; }
        public virtual Color Color { get; set; }
        public virtual ManufacturingYear ManufacturingYear { get; set; }
        public virtual Model Model { get; set; }
        public virtual PurchaseOrderDetail PurchaseOrderDetail { get; set; }
        public virtual SellOrder_Details SellOrder_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportDetail> ExportDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovementPermission> MovementPermissions { get; set; }
        public virtual Storing_Master Storing_Master { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WithdrawPerm> WithdrawPerms { get; set; }
    }
}
