//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deduction
    {
        public int Deduction_ID { get; set; }
        public string Deduction_Code { get; set; }
        public string Deduction_A_Name { get; set; }
        public string Deduction_E_Name { get; set; }
        public string Deduction_Description { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
    }
}
