//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers_Orders
    {
        public int Id { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Address { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual purchaseOrder purchaseOrder { get; set; }
        public virtual User User { get; set; }
    }
}
