//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class elRwadEntities : DbContext
    {
        public elRwadEntities()
            : base("name=elRwadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessory> Accessories { get; set; }
        public virtual DbSet<AddingPermission> AddingPermissions { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<CarsCategory> CarsCategories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Deputation> Deputations { get; set; }
        public virtual DbSet<Drivers_Orders> Drivers_Orders { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employees_Categories> Employees_Categories { get; set; }
        public virtual DbSet<Emplyees_Qualifications> Emplyees_Qualifications { get; set; }
        public virtual DbSet<ExportDetail> ExportDetails { get; set; }
        public virtual DbSet<ExportMain> ExportMains { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Group_Details> Group_Details { get; set; }
        public virtual DbSet<GroupsMaster> GroupsMasters { get; set; }
        public virtual DbSet<HR_Employee_Deductions> HR_Employee_Deductions { get; set; }
        public virtual DbSet<HR_Leave_Order> HR_Leave_Order { get; set; }
        public virtual DbSet<InsuranceCompany> InsuranceCompanies { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<ManufacturingYear> ManufacturingYears { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Mission> Missions { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<MovementPermission> MovementPermissions { get; set; }
        public virtual DbSet<Official_Vacation> Official_Vacation { get; set; }
        public virtual DbSet<OrderStatu> OrderStatus { get; set; }
        public virtual DbSet<Perm_Absent> Perm_Absent { get; set; }
        public virtual DbSet<PermissionType> PermissionTypes { get; set; }
        public virtual DbSet<ProcessStatu> ProcessStatus { get; set; }
        public virtual DbSet<Proj_Month> Proj_Month { get; set; }
        public virtual DbSet<Proj_Year> Proj_Year { get; set; }
        public virtual DbSet<purchaseOrder> purchaseOrders { get; set; }
        public virtual DbSet<PurchaseOrder_Accessories> PurchaseOrder_Accessories { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual DbSet<QualificationType> QualificationTypes { get; set; }
        public virtual DbSet<RecievedCarPermission> RecievedCarPermissions { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Sales_PurchaseOrder> Sales_PurchaseOrder { get; set; }
        public virtual DbSet<SellBill> SellBills { get; set; }
        public virtual DbSet<SellOrder> SellOrders { get; set; }
        public virtual DbSet<SellOrder_Details> SellOrder_Details { get; set; }
        public virtual DbSet<Sheet_Details> Sheet_Details { get; set; }
        public virtual DbSet<ShiftDetail> ShiftDetails { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<Showing_Branches> Showing_Branches { get; set; }
        public virtual DbSet<Specialty> Specialties { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Storing_Details> Storing_Details { get; set; }
        public virtual DbSet<Storing_Master> Storing_Master { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SuppliersRepresentative> SuppliersRepresentatives { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<University> Universities { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vacations_Orders> Vacations_Orders { get; set; }
        public virtual DbSet<Vacations_Types> Vacations_Types { get; set; }
        public virtual DbSet<Vendor_Items> Vendor_Items { get; set; }
        public virtual DbSet<WithdrawPerm> WithdrawPerms { get; set; }
        public virtual DbSet<Deduction> Deductions { get; set; }
    }
}
