//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees_Categories()
        {
            this.Employees = new HashSet<Employee>();
            this.Official_Vacation = new HashSet<Official_Vacation>();
            this.Vacations_Types = new HashSet<Vacations_Types>();
        }
    
        public int Category_ID { get; set; }
        public string Category_Code { get; set; }
        public string Name_A { get; set; }
        public string Name_E { get; set; }
        public string Description { get; set; }
        public Nullable<int> Work_Days_Week { get; set; }
        public Nullable<int> Work_Days_Month { get; set; }
        public Nullable<int> Work_Day_Hours { get; set; }
        public string Work_Day_Hours_From { get; set; }
        public string Work_Day_Hours_To { get; set; }
        public Nullable<byte> Calculate_Salary_DueTo { get; set; }
        public Nullable<short> Max_Absence_Days { get; set; }
        public Nullable<int> Year_Vacations { get; set; }
        public Nullable<double> Insurance_Percent { get; set; }
        public Nullable<double> Income_Taxes_Percent { get; set; }
        public Nullable<bool> Taxes_after_Absence { get; set; }
        public int User_ID { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Official_Vacation> Official_Vacation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacations_Types> Vacations_Types { get; set; }
    }
}
