//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emplyees_Qualifications
    {
        public int EmployeeId { get; set; }
        public Nullable<byte> QualifyTypeId { get; set; }
        public string Qualify { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> SpecialtyId { get; set; }
        public Nullable<int> GradYear { get; set; }
        public string GradProject { get; set; }
        public string TotalGrade { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual QualificationType QualificationType { get; set; }
        public virtual Specialty Specialty { get; set; }
        public virtual University University { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
