//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Branches = new HashSet<Branch>();
            this.Companies = new HashSet<Company>();
            this.Departments = new HashSet<Department>();
            this.Drivers_Orders = new HashSet<Drivers_Orders>();
            this.HR_Employee_Deductions = new HashSet<HR_Employee_Deductions>();
            this.HR_Employee_Deductions1 = new HashSet<HR_Employee_Deductions>();
            this.HR_Leave_Order = new HashSet<HR_Leave_Order>();
            this.Missions = new HashSet<Mission>();
            this.Missions1 = new HashSet<Mission>();
            this.MovementPermissions = new HashSet<MovementPermission>();
            this.Perm_Absent = new HashSet<Perm_Absent>();
            this.Stores = new HashSet<Store>();
            this.Vacations_Orders = new HashSet<Vacations_Orders>();
        }
    
        public int Employee_ID { get; set; }
        public string Employee_Code { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> City_ID { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> ImageID { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public Nullable<int> Job_ID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<System.DateTime> Assigment_Date { get; set; }
        public string LeaveReason { get; set; }
        public string Insurance_Number { get; set; }
        public bool Is_Insurance { get; set; }
        public double Basic_Salary { get; set; }
        public double Insurance_Salary { get; set; }
        public double Variable_Salary { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Last_User_ID { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
        public Nullable<System.DateTime> leave_Date { get; set; }
        public Nullable<System.DateTime> Insurance_Date { get; set; }
        public Nullable<System.DateTime> HealthCheck_Date { get; set; }
        public Nullable<System.DateTime> Insurnace_EndDate { get; set; }
        public Nullable<int> Deputation_ID { get; set; }
        public int WeekEndDay { get; set; }
        public Nullable<int> Shift_Id { get; set; }
        public Nullable<double> YearlySPInsurance_Basic { get; set; }
        public Nullable<double> YearlySPInsurance_Additional { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public string ZipCode { get; set; }
        public string Qualify { get; set; }
        public Nullable<int> University_ID { get; set; }
        public Nullable<byte> Qualify_Type { get; set; }
        public Nullable<int> Faculty_ID { get; set; }
        public Nullable<int> Specialty_ID { get; set; }
        public Nullable<int> Grad_Year { get; set; }
        public string Grad_Project { get; set; }
        public string Total_Grade { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch> Branches { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies { get; set; }
        public virtual Day Day { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        public virtual Deputation Deputation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drivers_Orders> Drivers_Orders { get; set; }
        public virtual Employees_Categories Employees_Categories { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Job Job { get; set; }
        public virtual QualificationType QualificationType { get; set; }
        public virtual University University { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Employee_Deductions> HR_Employee_Deductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Employee_Deductions> HR_Employee_Deductions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Leave_Order> HR_Leave_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mission> Missions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mission> Missions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovementPermission> MovementPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perm_Absent> Perm_Absent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store> Stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacations_Orders> Vacations_Orders { get; set; }
    }
}
