//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportDetail
    {
        public int ExportDetails_ID { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public int ExportMainID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual ExportMain ExportMain { get; set; }
    }
}
