//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExportMain()
        {
            this.ExportDetails = new HashSet<ExportDetail>();
        }
    
        public int ExportMainID { get; set; }
        public Nullable<bool> ForSale { get; set; }
        public Nullable<int> SellOrder_ID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> ToStoreID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportDetail> ExportDetails { get; set; }
        public virtual SellOrder SellOrder { get; set; }
        public virtual Store Store { get; set; }
        public virtual Store Store1 { get; set; }
    }
}
