//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Leave_Order
    {
        public int Order_ID { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<int> LeaveType_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public Nullable<double> Leave_Hours { get; set; }
        public Nullable<int> AccpetedBy_ID { get; set; }
        public Nullable<int> From_Hour { get; set; }
        public Nullable<int> From_Minute { get; set; }
        public Nullable<int> To_Hour { get; set; }
        public Nullable<int> To_Minute { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string Permission_Causes { get; set; }
        public Nullable<bool> DayOrNight { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public Nullable<System.DateTime> Approv_Date { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual PermissionType PermissionType { get; set; }
        public virtual Proj_Month Proj_Month { get; set; }
        public virtual Proj_Year Proj_Year { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
