//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovementPermission()
        {
            this.RecievedCarPermissions = new HashSet<RecievedCarPermission>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> StoreIDFrom { get; set; }
        public Nullable<int> CarID { get; set; }
        public string Address { get; set; }
        public Nullable<int> StoreIDTo { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Store Store { get; set; }
        public virtual Store Store1 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecievedCarPermission> RecievedCarPermissions { get; set; }
    }
}
