//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perm_Absent
    {
        public int PermAbsent_ID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> PermAbsent_FromDate { get; set; }
        public Nullable<System.DateTime> PermAbsent_ToDate { get; set; }
        public Nullable<int> Emp_ID { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public Nullable<System.DateTime> Approv_Date { get; set; }
        public Nullable<int> Approv_Emp { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
        public string Abs_Causes { get; set; }
        public Nullable<byte> count { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual Proj_Month Proj_Month { get; set; }
        public virtual Proj_Year Proj_Year { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
