//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PermissionType()
        {
            this.HR_Leave_Order = new HashSet<HR_Leave_Order>();
        }
    
        public int PermissionType_ID { get; set; }
        public string PermissionType_Name { get; set; }
        public string PermissionType_Name_EN { get; set; }
        public Nullable<bool> Salary_Deduc { get; set; }
        public Nullable<double> Deduc_Percent { get; set; }
        public Nullable<byte> Max_Times { get; set; }
        public Nullable<byte> Hours_Count { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Leave_Order> HR_Leave_Order { get; set; }
        public virtual User User { get; set; }
    }
}
