//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderDetail()
        {
            this.Cars = new HashSet<Car>();
            this.Storing_Details = new HashSet<Storing_Details>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> ManufacturingYearId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<int> ProcessStatusId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car> Cars { get; set; }
        public virtual CarsCategory CarsCategory { get; set; }
        public virtual Color Color { get; set; }
        public virtual ManufacturingYear ManufacturingYear { get; set; }
        public virtual Model Model { get; set; }
        public virtual ProcessStatu ProcessStatu { get; set; }
        public virtual purchaseOrder purchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storing_Details> Storing_Details { get; set; }
    }
}
