//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchaseOrder()
        {
            this.AddingPermissions = new HashSet<AddingPermission>();
            this.Drivers_Orders = new HashSet<Drivers_Orders>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.Storing_Master = new HashSet<Storing_Master>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> SupplierRepresentativeId { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string ReceivingAddress { get; set; }
        public Nullable<int> AddressRegionId { get; set; }
        public Nullable<int> AddressCityId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> IsApprovFinancialManag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddingPermission> AddingPermissions { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drivers_Orders> Drivers_Orders { get; set; }
        public virtual Region Region { get; set; }
        public virtual Showing_Branches Showing_Branches { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual SuppliersRepresentative SuppliersRepresentative { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storing_Master> Storing_Master { get; set; }
    }
}
