//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_PurchaseOrder
    {
        public int Id { get; set; }
        public int User_id { get; set; }
        public System.DateTime Date { get; set; }
        public string Buyer_Name { get; set; }
        public string Adress { get; set; }
        public Nullable<int> City_Id { get; set; }
        public Nullable<int> Region_Id { get; set; }
        public Nullable<int> Mob_Number { get; set; }
        public int SSN { get; set; }
        public Nullable<int> Brand_Id { get; set; }
        public Nullable<int> Model_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> Color_Id { get; set; }
        public string Internal_Color { get; set; }
        public Nullable<bool> CarStatus { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> HaveInsurance { get; set; }
        public Nullable<int> InsurCom_Id { get; set; }
        public Nullable<bool> IsApproval { get; set; }
        public string RefusalReasons { get; set; }
        public Nullable<double> Total_Price { get; set; }
        public Nullable<double> Deposit { get; set; }
        public Nullable<double> Remaining { get; set; }
        public Nullable<bool> Payment_Method { get; set; }
        public Nullable<int> Bank_Id { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual CarsCategory CarsCategory { get; set; }
        public virtual City City { get; set; }
        public virtual Color Color { get; set; }
        public virtual InsuranceCompany InsuranceCompany { get; set; }
        public virtual Model Model { get; set; }
        public virtual Region Region { get; set; }
        public virtual User User { get; set; }
    }
}
