//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellOrder()
        {
            this.ExportMains = new HashSet<ExportMain>();
            this.SellOrder_Details = new HashSet<SellOrder_Details>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string BuyerName { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Cityid { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> MobNumber { get; set; }
        public Nullable<int> SSN { get; set; }
        public Nullable<bool> Isapproval { get; set; }
        public string RefusalReasons { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportMain> ExportMains { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellOrder_Details> SellOrder_Details { get; set; }
        public virtual User User { get; set; }
    }
}
