//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellOrder_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellOrder_Details()
        {
            this.Cars = new HashSet<Car>();
            this.PurchaseOrder_Accessories = new HashSet<PurchaseOrder_Accessories>();
            this.WithdrawPerms = new HashSet<WithdrawPerm>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SellorderId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public string InternalColor { get; set; }
        public Nullable<bool> HaveInsurance { get; set; }
        public Nullable<int> InsurcomId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Totalprice { get; set; }
        public Nullable<double> Deposit { get; set; }
        public Nullable<double> Remaining { get; set; }
        public Nullable<bool> PaymentMethod { get; set; }
        public Nullable<int> BankId { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car> Cars { get; set; }
        public virtual CarsCategory CarsCategory { get; set; }
        public virtual Color Color { get; set; }
        public virtual InsuranceCompany InsuranceCompany { get; set; }
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder_Accessories> PurchaseOrder_Accessories { get; set; }
        public virtual SellOrder SellOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WithdrawPerm> WithdrawPerms { get; set; }
    }
}
