//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sheet_Details
    {
        public int Detail_ID { get; set; }
        public int TimeSheet_ID { get; set; }
        public int Employee_ID { get; set; }
        public string Enterance_Time { get; set; }
        public string Exit_Time { get; set; }
        public Nullable<int> Day_State { get; set; }
        public Nullable<System.DateTime> last_Update { get; set; }
        public Nullable<int> User_ID { get; set; }
    }
}
