//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specialty()
        {
            this.Emplyees_Qualifications = new HashSet<Emplyees_Qualifications>();
        }
    
        public int Specialty_ID { get; set; }
        public string Specialty_A_Name { get; set; }
        public string Specialty_E_Name { get; set; }
        public string Specialty_Notes { get; set; }
        public Nullable<int> Faculty_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emplyees_Qualifications> Emplyees_Qualifications { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
