//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storing_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Storing_Master()
        {
            this.Cars = new HashSet<Car>();
            this.Storing_Details = new HashSet<Storing_Details>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string ApprovalNo { get; set; }
        public Nullable<System.DateTime> AddingDate { get; set; }
        public Nullable<int> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car> Cars { get; set; }
        public virtual purchaseOrder purchaseOrder { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storing_Details> Storing_Details { get; set; }
        public virtual User User { get; set; }
    }
}
