//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliersRepresentative
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuppliersRepresentative()
        {
            this.purchaseOrders = new HashSet<purchaseOrder>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Job { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchaseOrder> purchaseOrders { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
