//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacations_Types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacations_Types()
        {
            this.Vacations_Orders = new HashSet<Vacations_Orders>();
        }
    
        public int VacationType_ID { get; set; }
        public string Type_Name { get; set; }
        public string Type_Name_EN { get; set; }
        public Nullable<int> Max_Days { get; set; }
        public Nullable<bool> Print_With_Reports { get; set; }
        public Nullable<int> Month_Max_Times { get; set; }
        public Nullable<int> Reg_Max_Month { get; set; }
        public Nullable<bool> With_Period { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public Nullable<bool> For_Emp_Type { get; set; }
        public Nullable<int> Emp_Type { get; set; }
        public string Notes { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
    
        public virtual Employees_Categories Employees_Categories { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacations_Orders> Vacations_Orders { get; set; }
    }
}
