//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGate.ElRwad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Items
    {
        public int Vendor_ID { get; set; }
        public int Item_ID { get; set; }
        public Nullable<bool> Pref_Vendor_Flag { get; set; }
        public Nullable<decimal> Last_Purchase_Price { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
    }
}
